import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/cors/Header";
import Footer from "@/components/cors/Footer";
import Provider from "@/utils/Provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// pages/_app.tsx or app/layout.tsx (depending on your Next.js version)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative`}
        suppressHydrationWarning={true}>
        <Provider>
          <Header />
          <section className="my-14 container">{children}</section>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
